{% set name = "napari-imc" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-imc-{{ version }}.tar.gz
  sha256: 705015bc70414ff63588bdc4a19c9fae9f203696830987edc27265a573fb00bd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7
    - qtpy
    - readimc >=0.5.0
    - superqt

test:
  imports:
    - napari_imc
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BodenmillerGroup/napari-imc
  summary: Imaging Mass Cytometry (IMC) file type support for napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - jwindhager
